### PR TITLE
Make sure to catch erroneous input for processMessageFiles

### PR DESCRIPTION
**Pull request by Pomax**
specifically due to seeing this on a production attempt: https://dashboard.heroku.com/apps/learning-mozilla-org-prod/activity/builds/c90a8064-257c-459b-a69d-8eba0c0443ed

### CODE REVIEW

**Comment by alanmoo** [comment]
LGTM

**Comment by Pomax** [comment]
not sure if you want to turn on "squash" for merges - if not I'll merge this in, but if so let me know and I'll wait for the squash option to show up in the merge button

**Comment by alanmoo** [comment]
Hmmm...that's something else we should have defined in mofo-standards...

On Sat, Aug 20, 2016 at 11:58 AM Mike Kamermans

<
mailto:Mike Kamermans <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

not sure if you want to turn on "squash" for merges - if not I'll merge this in, but if so let me know and I'll wait for the squash option to show up in the merge button

—

You are receiving this because you were assigned.

Reply to this email directly,
https://github.com/mozilla/pontoon-to-json/pull/1#issuecomment-241207878
, or

**Comment by Pomax** [comment]
filed as https://github.com/MozillaFoundation/mofo-standards/issues/18 -- let me know whether you want this squashed.

**Comment by alanmoo** [comment]
Squash it

**Pull request merged**
